import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MetaInside-DApp",
  description: "Generated by MetaInside",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              /**
               * This function captures uncaught exceptions that occur within the iframe.
               */
              window.onerror = function (message, source, lineno, colno, error) {
                // Package the error details into a structured object.
                const errorPayload = {
                  message: message,
                  source: source, // The URL of the script where the error occurred
                  lineno: lineno,
                  colno: colno,
                  stack: error ? error.stack : 'No stack available'
                };

                // Send the error details to the parent window.
                // For security, in production you should replace '*' with your main app's origin,
                // e.g., 'https://metainside.io'
                window.parent.postMessage({
                  type: 'iframeError',
                  payload: errorPayload
                }, '*');

                // Return true to prevent the error from being logged to the console a second time.
                return true;
              };

              /**
               * This listener captures unhandled promise rejections.
               */
              window.addEventListener('unhandledrejection', event => {
                window.parent.postMessage({
                  type: 'iframeError',
                  payload: {
                    message: 'Unhandled promise rejection: ' + (event.reason.message || event.reason),
                    stack: event.reason.stack || 'No stack available'
                  }
                }, '*');
              });
            `,
          }}
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
